---
abstract: 'Parses verb structures into modal, tense, & infinitive.'
author:
  - 'Chris Meyer <chris@mytechs.com>'
  - 'Josiah Bryan <jbryan@cpan.org>'
  - 'John Napiorkowski <jjnapiork@cpan.org>'
build_requires:
  Test::Most: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300020, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lingua-EN-VerbTense
resources:
  bugtracker: https://github.com/jjn1056/Lingua-EN-VerbTense/issues
  homepage: https://github.com/jjn1056/Lingua-EN-VerbTense
  repository: https://github.com/jjn1056/Lingua-EN-VerbTense.git
version: 3.001
